title: missingSemicolon
subtitle: A Portfolio Jekyll Theme Built for Developers
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a beautiful Jekyll Theme Built For Developers, which is optimized for speed and readability.

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Blog
      url: /blog
    # - text: Gallery
    #   url: /gallery
    # - text: Shop
    #   url : /shop
    # - text: Contact
    #   url : /contact
    # - text: Styleguide
      # url: /styleguide
    # - text: Get Started
      # url: /get-started

# Edit Author details (For multi authors check _data/authors.yml)

author_logo: bitmoji.png
author: David Hunter
author_bio: Hi, my name is David Hunter and I have a passion for building software.
author_email: "davidhunter123.dh@gmail.com"
author_location: Colorado
typewrite-text: David is usually right about his assumptions

# Experiences
author_work_experiences:
            - company_name: TODO
              company_logo: google.png
              company_url: https://google.com
              designation: TODO
              description: TODO
              visibility: true
            - company_name: TODO
              company_logo: microsoft.png
              company_url: https://microsoft.com
              designation: TODO
              description: TODO
              visibility: true

# Education
author_education_details:
              - college_logo: mines.jpeg
                college_name: Colorado School of Mines
                college_url: https://mines.edu
                college_degree: Computer Science
                description: Bachelor of Science
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: gamershub.png
                project_title: TODO
                project_description: TODO
                project_url: https://gamershub.in
                visibility: true
              - project_thumbnail: hack4r.PNG
                project_title: TODO
                project_description: TODO
                project_url: https://hack4r.com
                visibility: true

# social links
# twitter_username: johndoe
github_username:  hunthunt2010
# facebook_username: johndoe
linkedin_username: david-hunter-0b223857
# behance_username: johndoe
# instagram_username: johndoe
# medium_username: johndoe
# telegram_username: johndoe
# dribbble_username: johndoe
# flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: missingSemicolon4

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
formspree_email: johndoe@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
